name: MythicKillCount
version: '1.0-SNAPSHOT'
main: crystal.MythicKillCount.MythicKillCount
api-version: '1.20'
depend: [PlaceholderAPI,MythicMobs]
commands:
  mythickillcount:
    description:
    usage: /mythickillcount <option> <target> <mobID> <value>
    aliases: [mkc]
